version: '2.4'

services:
  mysql:
    container_name: mysql_620098373
    ports:
      - 3306:3306
    image: mysql:8.0
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql
      - ./init.sql:/tmp/init.sql:Z
  mongo:
    container_name: mongo_620098373
    ports:
      - 27017:27017
    image: mongo:4.4
    volumes:
      - mongo-db-data:/data/db
volumes:
  mysql-db-data:
  mongo-db-data:
